CompileFlags:
  Add: [-xc++, -std=c++17, -Wall, -Wno-missing-prototypes]
Diagnostics:
  ClangTidy:
    Add: [performance*, modernize*, readability*]
    Remove: [modernize-use-trailing-return-type, modernize-use-nodiscard, readability-braces-around-statements, readability-magic-numbers]
