
[theme]
name = "/home/andrew/config/home/.config/i3status-rs/theme.toml"

[icons]
name = "none"
[icons.overrides]
headphones = "🤆"
uptime = "⧗"
cpu = "⧈"
net_wired = "🖧"
memory_mem = "*"
time = "◍"
music = "♫"
music_play = "▷"
music_pause = "🞐"
music_next = "➟"

[[block]]
block = "focused_window"
max_width = 100
show_marks = "all"

#[[block]]
#block = "custom"
#command='''/home/andrew/.local/bin/sp metadata | awk -F "|" '/title/{print $2} /artist/{printf "♫ %s | ", $2}' '''
#on_click='''/home/andrew/.local/bin/sp play'''

[[block]]
block = "music"
buttons = ["play", "next"]
max_width = 40
marquee_interval = 10
marquee_speed = 0.2
hide_when_empty = true
format = "{artist}: {title}"
dynamic_width = true

[[block]]
block = "bluetooth"
mac = "38:18:4C:3E:17:6C"
format = "WH-1000MX"

[[block]]
block = "bluetooth"
mac = "A9:9A:BA:01:A4:6A"
format = "CY-100"

[[block]]
block = "custom"
command=''' echo "do today's best" '''

#[[block]]
#block = "pomodoro"
#length = 15
#break_length = 7
#message = "Time for break!"
#break_message = "Time for work!"
#use_nag = true

[[block]]
block = "net"
device = "enp6s0"
format = "{ip} {graph_up} {graph_down}"
interval = 3 
icons_format = " "

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;K} {mem_used_percents}"
icons_format = " "

[[block]]
block = "cpu"
interval = 3
format = "{frequency} {barchart}"
icons_format = " "

[[block]]
block = "uptime"
icons_format = " "

[[block]]
block = "time"
interval = 1
format = "%a, %b %d %r"
icons_format = " "
