idle_bg = "#323232ee"
idle_fg = "#eddedd"
info_bg = "#323232ee"
info_fg = "#eddedd"
good_bg = "#323232ee"
good_fg = "#95d920"
warning_bg  = "#323232ee"
warning_fg  = "#b58900"
critical_bg = "#323232ee"
critical_fg = "#dc322f"
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#000000"
separator_bg = "#323232ee"
separator_fg = "#727252"
separator = "/"
