idle_bg = "#373432ed"
idle_fg = "#fff8d8"
info_bg = "#373432ed"
info_fg = "#fff8d8"
good_bg = "#373432ed"
good_fg = "#6b9614"
warning_bg  = "#373432ed"
warning_fg  = "#e8b032"
critical_bg = "#373432ed"
critical_fg = "#cc3307"
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#000000"
separator_bg = "#373432ed"
separator_fg = "#68625d"
separator = "/"
